To Do list: list structure
BouaikIlham/To-Do-list- pull request #1
Opened 2022-05-04 16:22 UTC by BouaikIlham

- [ ] Created an index.html file. 
- [ ] Created an empty To Do List placeholder(<div> or <ul> element). The index.html file  set template using the HTML Webpack Plugin.
- [ ] Created an index.js file and set an array of some simple to do tasks (array of objects). Each task object  contain three keys:
      description [string].
      completed [bool].
      index: [number].
- [ ] WritedOn page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
- [ ] Created a style.css and set rules for the To Do List
- [ ]  CSS All my source files (index.html, index.js and style.css)  located in /src directory, and my distribution files will generated by webpack and served by webpack dev server from /dist folder. 
- [ ] loaded by Webpack Style/CSS Loader.

2022-05-04 21:58 UTC, brytebee requested changes
Hi, @BouaikIlham👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- ✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 21:58 UTC, brytebee commented on package.json
> +    "build": "webpack --mode production"
- [ ] **Optional:** The steps to run your code isn't specified and the general start script is missing. Kindly add `"start": "webpack serve --open"` to `package.json` script section.
- [x] **Optional** Kindly update your scripts with the below :
 `"build": "webpack",
    "watch": "webpack --watch",
    "start": "webpack serve --open"`

2022-05-04 21:58 UTC, brytebee commented on src/index.js
> +
- [ ] **Required:** Great job implementing this. 👏 However, the To-do list should be rendered in the order of their index. Kindly sort by their indexes before displaying.
Consider this:
`Array.sort((a, b) => a.index - b.index);`

2022-05-05 07:53 UTC, julie-ify approved these changes
Hi @BouaikIlham, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 08:10 UTC, merged